# Basic Optimization
In this example, we'll be performing a simple optimization of single-objective functions using the global-best optimizer in `pyswarms.single.GBestPSO` and the local-best optimizer in `pyswarms.single.LBestPSO`. This aims to demonstrate the basic capabilities of the library when applied to benchmark problems.

In [1]:
import sys
# Change directory to access the pyswarms module
sys.path.append('../')

In [2]:
print('Running on Python version: {}'.format(sys.version))

Running on Python version: 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]


In [3]:
# Import modules
import numpy as np

# Import PySwarms
import pyswarms as ps
from pyswarms.utils.functions import single_obj as fx

# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

## Optimizing a function
First, let's start by optimizing the sphere function. Recall that the minima of this function can be located at `f(0,0..,0)` with a value of `0`. In case you don't remember the characteristics of a given function, simply call `help(<function>)`.

For now let's just set some arbitrary parameters in our optimizers. There are, at minimum, three steps to perform optimization:

1. Set the hyperparameters to configure the swarm as a `dict`.
2. Create an instance of the optimizer by passing the dictionary along with the necessary arguments.
3. Call the `optimize()` method and have it store the optimal cost and position in a variable.

The `optimize()` method returns a `tuple` of values, one of which includes the optimal cost and position after optimization. You can store it in a single variable and just index the values, or unpack it using several variables at once.

In [7]:
%%time
# Set-up hyperparameters
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

# Call instance of PSO
optimizer = ps.single.GlobalBestPSO(n_particles=10, dimensions=2, options=options)

# Perform optimization
cost, pos = optimizer.optimize(fx.sphere, iters=10)

2019-04-24 18:23:08,556 - pyswarms.single.global_best - INFO - Optimize for 10 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}

pyswarms.single.global_best:   0%|          |0/10
pyswarms.single.global_best:   0%|          |0/10, best_cost=0.0605
pyswarms.single.global_best:   0%|          |0/10, best_cost=0.0605
pyswarms.single.global_best:   0%|          |0/10, best_cost=0.0605
pyswarms.single.global_best:   0%|          |0/10, best_cost=0.0605
pyswarms.single.global_best:   0%|          |0/10, best_cost=0.0605
pyswarms.single.global_best:   0%|          |0/10, best_cost=0.0424
pyswarms.single.global_best:   0%|          |0/10, best_cost=8.36e-06
pyswarms.single.global_best:   0%|          |0/10, best_cost=8.36e-06
pyswarms.single.global_best:  80%|████████  |8/10, best_cost=8.36e-06
pyswarms.single.global_best:  80%|████████  |8/10, best_cost=8.36e-06
pyswarms.single.global_best:  80%|████████  |8/10, best_cost=8.36e-06
pyswarms.single.global_best: 100%|██████████|10/10, best_cost=8.36e-

CPU times: user 52 ms, sys: 0 ns, total: 52 ms
Wall time: 157 ms


In [13]:
z=np.array(optimizer.cost_history)

In [16]:
z[z.argmin()]

8.356164158276717e-06

In [18]:
fx.sphere(pos.T)

AxisError: axis 1 is out of bounds for array of dimension 1

In [23]:
pos.T

array([ 0.00249681, -0.00145674])

In [33]:
(pos.reshape(-1, 1) ** 2).sum(axis=1)

array([6.23406772e-06, 2.12209644e-06])

In [30]:
fx.sphere(pos.reshape(-1, 1))

array([6.23406772e-06, 2.12209644e-06])

In [29]:
pos

array([ 0.00249681, -0.00145674])

In [34]:
cost

8.356164158276717e-06

In [35]:
dir(optimizer)

['ToHistory',
 '__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_populate_history',
 'bh',
 'bounds',
 'center',
 'cost_history',
 'dimensions',
 'ftol',
 'init_pos',
 'mean_neighbor_history',
 'mean_pbest_history',
 'n_particles',
 'name',
 'optimize',
 'options',
 'pos_history',
 'rep',
 'reset',
 'swarm',
 'swarm_size',
 'top',
 'velocity_clamp',
 'velocity_history',
 'vh']

In [36]:
optimizer.pos_history

[array([[0.90124935, 0.17491093],
        [0.80474654, 0.92141545],
        [0.82737053, 0.08275101],
        [0.43055521, 0.16029267],
        [0.7748099 , 0.83678948],
        [0.21088674, 0.49822131],
        [0.35918509, 0.7553067 ],
        [0.10156838, 0.22410303],
        [0.58793823, 0.30151857],
        [0.17084816, 0.75461516]]), array([[1.43727288, 0.58528291],
        [0.93435275, 1.42905162],
        [1.13856742, 0.33461069],
        [0.72586063, 0.32709616],
        [1.5094666 , 1.18965563],
        [0.90403286, 0.49314525],
        [0.67649282, 1.00266235],
        [0.5043016 , 0.67703065],
        [0.75097075, 0.41294503],
        [0.4881155 , 0.80689386]]), array([[1.65419275, 0.77490286],
        [0.77212441, 1.42704143],
        [0.98198008, 0.50241268],
        [0.79360331, 0.46185756],
        [1.7394455 , 1.39718321],
        [1.34641821, 0.40948887],
        [0.9158877 , 1.14369282],
        [0.67208624, 0.96319035],
        [0.70009302, 0.44887179],
        [0.5

In [37]:
optimizer.cost_history

[0.06053830594849705,
 0.06053830594849705,
 0.06053830594849705,
 0.06053830594849705,
 0.06053830594849705,
 0.042371607406169756,
 8.356164158276717e-06,
 8.356164158276717e-06,
 8.356164158276717e-06,
 8.356164158276717e-06]

In [51]:
np.argmin(fx.sphere(optimizer.pos_history[np.argmin(optimizer.cost_history)]))

8

In [43]:
np.argmin(optimizer.cost_history)

6

In [46]:
optimizer.pos_history[6]

array([[-0.75208666,  0.13358625],
       [ 0.05030533, -0.27457037],
       [-0.30552283,  0.12318309],
       [ 0.03198256,  0.00709269],
       [-0.23476459, -0.06529374],
       [-0.9488298 ,  0.25177129],
       [-0.40068151,  0.07099387],
       [-0.14094749, -0.28401897],
       [ 0.00249681, -0.00145674],
       [ 0.19438228, -0.01001684]])

In [72]:
optimizer.pos_history[np.argmin(optimizer.cost_history)][np.argmin(fx.sphere(optimizer.pos_history[np.argmin(optimizer.cost_history)]))]

array([ 0.00249681, -0.00145674])

In [73]:
pos

array([ 0.00249681, -0.00145674])

In [74]:
min_cost_idx = np.argmin(optimizer.cost_history)
min_cost_idx

6

In [75]:
min_pos_idx = np.argmin(fx.sphere(optimizer.pos_history[min_cost_idx]))
min_pos_idx

8

In [76]:
optimizer.pos_history[min_cost_idx][min_pos_idx]

array([ 0.00249681, -0.00145674])

In [77]:
optimizer.cost_history[min_cost_idx] == cost

True

In [78]:
np.array_equal(optimizer.pos_history[min_cost_idx][min_pos_idx], pos)

True

We can see that the optimizer was able to find a good minima as shown above. You can control the verbosity of the output using the `verbose` argument, and the number of steps to be printed out using the `print_step` argument.

Now, let's try this one using local-best PSO:

In [5]:
%%time
# Set-up hyperparameters
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9, 'k': 2, 'p': 2}

# Call instance of PSO
optimizer = ps.single.LocalBestPSO(n_particles=10, dimensions=2, options=options)

# Perform optimization
cost, pos = optimizer.optimize(fx.sphere, print_step=100, iters=1000, verbose=3)

INFO:pyswarms.single.local_best:Iteration 1/1000, cost: 0.01379181672220725
INFO:pyswarms.single.local_best:Iteration 101/1000, cost: 2.084056061999154e-07
INFO:pyswarms.single.local_best:Iteration 201/1000, cost: 9.44588224259351e-10
INFO:pyswarms.single.local_best:Iteration 301/1000, cost: 1.5414149511766008e-13
INFO:pyswarms.single.local_best:Iteration 401/1000, cost: 3.283944854760787e-16
INFO:pyswarms.single.local_best:Iteration 501/1000, cost: 2.093366830537641e-20
INFO:pyswarms.single.local_best:Iteration 601/1000, cost: 5.0279508047072096e-24
INFO:pyswarms.single.local_best:Iteration 701/1000, cost: 1.0492646748670006e-27
INFO:pyswarms.single.local_best:Iteration 801/1000, cost: 2.2616819643931453e-29
INFO:pyswarms.single.local_best:Iteration 901/1000, cost: 8.48269618909152e-35
INFO:pyswarms.single.local_best:================================
Optimization finished!
Final cost: 0.0000
Best value: [2.122881378865588e-18, -5.35447408455737e-19]



CPU times: user 355 ms, sys: 4.36 ms, total: 359 ms
Wall time: 353 ms


## Optimizing a function with bounds
Another thing that we can do is to set some bounds into our solution, so as to contain our candidate solutions within a specific range. We can do this simply by passing a `bounds` parameter, of type `tuple`, when creating an instance of our swarm. Let's try this using the global-best PSO with the Rastrigin function (`rastrigin` in `pyswarms.utils.functions.single_obj`).

Recall that the Rastrigin function is bounded within `[-5.12, 5.12]`. If we pass an unbounded swarm into this function, then a `ValueError` might be raised. So what we'll do is to create a bound within the specified range. There are some things to remember when specifying a bound:

* A bound should be of type tuple with length 2. 
* It should contain two `numpy.ndarrays` so that we have a `(min_bound, max_bound)`
* Obviously, all values in the `max_bound` should always be greater than the `min_bound`. Their shapes should match the dimensions of the swarm.

What we'll do now is to create a 10-particle, 2-dimensional swarm. This means that we have to set our maximum and minimum boundaries with the shape of 2. In case we want to initialize an n-dimensional swarm, we then have to set our bounds with the same shape n. A fast workaround for this would be to use the `numpy.ones` function multiplied by a constant.

In [6]:
# Create bounds
max_bound = 5.12 * np.ones(2)
min_bound = - max_bound
bounds = (min_bound, max_bound)

In [7]:
%%time
# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

# Call instance of PSO with bounds argument
optimizer = ps.single.GlobalBestPSO(n_particles=10, dimensions=2, options=options, bounds=bounds)

# Perform optimization
cost, pos = optimizer.optimize(fx.rastrigin, print_step=100, iters=1000, verbose=3)

INFO:pyswarms.single.global_best:Iteration 1/1000, cost: 12.243865048066269
INFO:pyswarms.single.global_best:Iteration 101/1000, cost: 1.1759164022634394
INFO:pyswarms.single.global_best:Iteration 201/1000, cost: 0.9949603350768896
INFO:pyswarms.single.global_best:Iteration 301/1000, cost: 0.9949590581556009
INFO:pyswarms.single.global_best:Iteration 401/1000, cost: 0.9949590570934177
INFO:pyswarms.single.global_best:Iteration 501/1000, cost: 0.9949590570932898
INFO:pyswarms.single.global_best:Iteration 601/1000, cost: 0.9949590570932898
INFO:pyswarms.single.global_best:Iteration 701/1000, cost: 0.9949590570932898
INFO:pyswarms.single.global_best:Iteration 801/1000, cost: 0.9949590570932898
INFO:pyswarms.single.global_best:Iteration 901/1000, cost: 0.9949590570932898
INFO:pyswarms.single.global_best:================================
Optimization finished!
Final cost: 0.9950
Best value: [3.5850411183743393e-09, -0.9949586379966202]



CPU times: user 213 ms, sys: 7.55 ms, total: 221 ms
Wall time: 210 ms


## Basic Optimization with Arguments

Here, we will run a basic optimization using an objective function that needs parameterization.  We will use the ``single.GBestPSO`` and a version of the rosenbrock function to demonstrate

In [2]:
import sys
# change directory to access pyswarms
sys.path.append('../')

print("Running Python {}".format(sys.version))

Running Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


In [8]:
# import modules
import numpy as np

# create a parameterized version of the classic Rosenbrock unconstrained optimzation function
def rosenbrock_with_args(x, a, b, c=0):

    f = (a - x[:, 0]) ** 2 + b * (x[:, 1] - x[:, 0] ** 2) ** 2 + c
    return f

### Using Arguments

Arguments can either be passed in using a tuple or a dictionary, using the ``kwargs={}`` paradigm. First lets optimize the Rosenbrock function using keyword arguments.  Note in the definition of the Rosenbrock function above, there were two arguments that need to be passed other than the design variables, and one optional keyword argument, ``a``, ``b``, and ``c``, respectively

In [12]:
from pyswarms.single.global_best import GlobalBestPSO

# instatiate the optimizer
x_max = 10 * np.ones(2)
x_min = -1 * x_max
bounds = (x_min, x_max)
options = {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
optimizer = GlobalBestPSO(n_particles=10, dimensions=2, options=options, bounds=bounds)

# now run the optimization, pass a=1 and b=100 as a tuple assigned to args

cost, pos = optimizer.optimize(rosenbrock_with_args, 1000, print_step=100, verbose=3, a=1, b=100, c=0)

INFO:pyswarms.single.global_best:Arguments Passed to Objective Function: {'c': 0, 'b': 100, 'a': 1}
INFO:pyswarms.single.global_best:Iteration 1/1000, cost: 1022.9667801907804
INFO:pyswarms.single.global_best:Iteration 101/1000, cost: 0.0011172801146408992
INFO:pyswarms.single.global_best:Iteration 201/1000, cost: 7.845605970774126e-07
INFO:pyswarms.single.global_best:Iteration 301/1000, cost: 1.313503109901238e-09
INFO:pyswarms.single.global_best:Iteration 401/1000, cost: 5.187079604907219e-10
INFO:pyswarms.single.global_best:Iteration 501/1000, cost: 1.0115283486088853e-10
INFO:pyswarms.single.global_best:Iteration 601/1000, cost: 2.329870757208421e-13
INFO:pyswarms.single.global_best:Iteration 701/1000, cost: 4.826176894160183e-15
INFO:pyswarms.single.global_best:Iteration 801/1000, cost: 3.125715456651088e-17
INFO:pyswarms.single.global_best:Iteration 901/1000, cost: 1.4236768129666014e-19
INFO:pyswarms.single.global_best:================================
Optimization finished!
Fina

It is also possible to pass a dictionary of key word arguments by using ``**`` decorator when passing the dict

In [13]:
kwargs={"a": 1.0, "b": 100.0, 'c':0}
cost, pos = optimizer.optimize(rosenbrock_with_args, 1000, print_step=100, verbose=3, **kwargs)

INFO:pyswarms.single.global_best:Arguments Passed to Objective Function: {'c': 0, 'b': 100.0, 'a': 1.0}
INFO:pyswarms.single.global_best:Iteration 1/1000, cost: 1.996797703363527e-21
INFO:pyswarms.single.global_best:Iteration 101/1000, cost: 1.0061676299213387e-24
INFO:pyswarms.single.global_best:Iteration 201/1000, cost: 4.8140236741112245e-28
INFO:pyswarms.single.global_best:Iteration 301/1000, cost: 2.879342304056693e-29
INFO:pyswarms.single.global_best:Iteration 401/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 501/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 601/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 701/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 801/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 901/1000, cost: 0.0
INFO:pyswarms.single.global_best:================================
Optimization finished!
Final cost: 0.0000
Best value: [1.0, 1.0]



Any key word arguments in the objective function can be left out as they will be passed the default as defined in the prototype. Note here, ``c`` is not passed into the function.

In [14]:
cost, pos = optimizer.optimize(rosenbrock_with_args, 1000, print_step=100, verbose=3, a=1, b=100)

INFO:pyswarms.single.global_best:Arguments Passed to Objective Function: {'b': 100, 'a': 1}
INFO:pyswarms.single.global_best:Iteration 1/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 101/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 201/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 301/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 401/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 501/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 601/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 701/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 801/1000, cost: 0.0
INFO:pyswarms.single.global_best:Iteration 901/1000, cost: 0.0
INFO:pyswarms.single.global_best:================================
Optimization finished!
Final cost: 0.0000
Best value: [1.0, 1.0]

